version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: development.Dockerfile
    env_file:
      - './frontend/.env.development.local'

  backend:
    environment:
      - NODE_ENV=development
    command: "yarn develop"

  nginx:
    build:
      context: ./nginx
      dockerfile: development.Dockerfile
    volumes:
      - ./nginx/default.development.conf:/etc/nginx/conf.d/nginx.conf
