version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: development.Dockerfile
    volumes:
      - ./frontend:/usr/src/frontend
      - /usr/src/frontend/node_modules
      - /usr/src/frontend/.next
    env_file:
      - './frontend/.env.development.local'
    depends_on:
      - backend

  backend:
    image: strapi/strapi
    volumes:
      - ./backend:/srv/app

  nginx:
    build:
      context: ./nginx
      dockerfile: development.Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.development.conf:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - backend
      - frontend
