version: 3
services:
  frontend:
    image: rushelex/chaos-control-book_frontend:console
    env_file:
      - ./frontend/.env.production.local

  backend:
    image: rushelex/chaos-control-book_backend:0.0.0
    environment:
      - NODE_ENV=production

  nginx:
    ports:
      - "443:443"
    volumes:
      - ./nginx/default.production.conf:/etc/nginx/conf.d/nginx.conf
      - /etc/ssl/chaoscontrol.xyz_ca.crt:/etc/ssl/chaoscontrol.xyz_ca.crt
      - /etc/ssl/chaoscontrol.xyz.crt:/etc/ssl/chaoscontrol.xyz.crt
      - /etc/ssl/chaoscontrol.xyz.key:/etc/ssl/chaoscontrol.xyz.key
