version: 3
services:
  frontend:
    container_name: frontend
    volumes:
      - ./frontend:/srv/app
      - /srv/app/node_modules
      - /srv/app/.next

  backend:
    container_name: backend
    image: strapi/strapi
    volumes:
      - ./backend:/srv/app
      - /srv/app/node_modules

  nginx:
    container_name: nginx
    image: nginx:stable
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
