version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: production.Dockerfile
    env_file:
      - './frontend/.env.production.local'

  backend:
    environment:
      - NODE_ENV=production
    command: 'yarn build && yarn start'

  nginx:
    build:
      context: ./nginx
      dockerfile: production.Dockerfile
    volumes:
      - ./nginx/default.production.conf:/etc/nginx/conf.d/nginx.conf
      - /etc/ssl/chaoscontrol.xyz_ca.crt:/etc/ssl/chaoscontrol.xyz_ca.crt
      - /etc/ssl/chaoscontrol.xyz.crt:/etc/ssl/chaoscontrol.xyz.crt
      - /etc/ssl/chaoscontrol.xyz.key:/etc/ssl/chaoscontrol.xyz.key
