version: "3"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: development.Dockerfile
    env_file:
      - ./frontend/.env.development.local

  backend:
    build:
      context: ./backend
      dockerfile: development.Dockerfile

  nginx:
    volumes:
      - ./nginx/default.development.conf:/etc/nginx/conf.d/nginx.conf
