version: '3'
services:
  frontend:
    volumes:
      - ./frontend:/usr/src/frontend
      - /usr/src/frontend/node_modules
      - /usr/src/frontend/.next
    depends_on:
      - backend

  backend:
    image: strapi/strapi
    volumes:
      - ./backend:/srv/app

  nginx:
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
